# Generated by Django 5.1.5 on 2025-01-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_scopes_alter_scope_article'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together=set(),
        ),
    ]
